base_url = "https://portfolio.vastorigins.com"
compile_sass = true
build_search_index = false
theme = "oceanic-zen"
title = "Portfolio - Edward"
description = "Goodies and perks."
taxonomies = [
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
highlight_code = true

[extra]
author = "Edward A."
github = "ffimnsr"
twitter = "ffimnsr"